name: Test PR Trigger

on:
  pull_request_target:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run a simple step
        run: echo "Hello from the PR trigger!"
